set x

diff --git a/jobs/sanity-tests/templates/bin/run b/jobs/sanity-tests/templates/bin/run
--- a/jobs/sanity-tests/templates/bin/run
+++ b/jobs/sanity-tests/templates/bin/run
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -e # exit immediately if a simple command exits with a non-zero status
+set -ex # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 export PATH=$PATH:/var/vcap/packages/redis-5/bin
