Testing what the master variables in the template
Signed-off-by: Kirubakaran Kuppusamy <kirubakaran.kuppasamy@santander.co.uk>

diff --git a/jobs/sanity-tests/templates/bin/run b/jobs/sanity-tests/templates/bin/run
--- a/jobs/sanity-tests/templates/bin/run
+++ b/jobs/sanity-tests/templates/bin/run
@@ -1,11 +1,14 @@
 #!/bin/bash
 
-set -e # exit immediately if a simple command exits with a non-zero status
+set -ex # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 export PATH=$PATH:/var/vcap/packages/redis-5/bin
 
 EXITSTATUS=0
+
+test_master1=<%= p("master_host") %>
+test_master2=<%= link("redis").instances.find {|redis| redis.bootstrap }.address %>
 
 master=<%= p("master_host", link("redis").instances.find {|redis| redis.bootstrap }.address) %>
 slave=<%= link("redis").instances.find {|redis| !redis.bootstrap }.address %>
