Fixing sanity tests
Signed-off-by: Alex Mirkhaydarov <alex.mirkhaydarov@servexternos.gruposantander.com>

#174769030

diff --git a/jobs/sanity-tests/templates/bin/run.erb b/jobs/sanity-tests/templates/bin/run.erb
--- a/jobs/sanity-tests/templates/bin/run.erb
+++ b/jobs/sanity-tests/templates/bin/run.erb
@@ -1,14 +1,22 @@
 #!/bin/bash
 
-set -e # exit immediately if a simple command exits with a non-zero status
+set -ex # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 export PATH=$PATH:/var/vcap/packages/redis-5/bin
 
 EXITSTATUS=0
 
-master=<%= p("master_host", link("redis").instances.find {|redis| redis.bootstrap }.address) %>
-slave=<%= link("redis").instances.find {|redis| !redis.bootstrap }.address %>
+master_host=$(redis-cli -h 127.0.0.1 -p 6379 -a <%= p("password") %> info | grep master_host | cut -d ':' -f 2 | tr -d '\r')
+echo <%= link("redis").instances.find { |redis| puts redis } %> > /tmp/instance_output
+cat /tmp/instance_output
+
+slave_host=<%= link("redis").instances.find { |redis| puts redis } %>
+
+slave=<%= link("redis").instances.find { |redis| !redis.bootstrap }.address %>
+
+master=<%= p("master_host", link("redis").instances.find { |redis| redis.bootstrap }.address) %>
+slave=<%= link("redis").instances.find { |redis| !redis.bootstrap }.address %>
 port="<%= link('redis').p('port') %>"
 password="<%= link('redis').p('password') %>"
 
